import type { PrismaClient } from "@prisma/client";
import { SEED_IDS } from "../ids.js";

const u = SEED_IDS.user;
const d = SEED_IDS.deal;

export async function seedDealsStatusHistoryAndNotes(prisma: PrismaClient): Promise<void> {
  await prisma.deal.createMany({
    data: [
      {
        id: d.D1,
        propertyAddress: "742 Evergreen Terrace, Fort Worth, TX",
        sellerName: "Homer S.",
        buyerName: null,
        acquisitionsRepId: u.REP_ACQ_JORDAN,
        dispoRepId: u.REP_DISPO_ALEX,
        transactionCoordinatorId: u.TC,
        contractDate: new Date("2026-01-10"),
        assignedDate: null,
        closedFundedDate: null,
        inspectionEndDate: null,
        contractPrice: 195000,
        assignmentPrice: null,
        assignmentFee: null,
        buyerEmdAmount: null,
        buyerEmdReceived: false,
        titleCompany: "Alamo Title",
        status: "LEAD",
      },
      {
        id: d.D2,
        propertyAddress: "4521 Oak Lane, Dallas, TX",
        sellerName: "Martha Quinn",
        buyerName: "TBD",
        acquisitionsRepId: u.REP_ACQ_SARAH,
        dispoRepId: u.REP_DISPO_CASEY,
        transactionCoordinatorId: u.TC,
        contractDate: new Date("2026-01-22"),
        assignedDate: null,
        closedFundedDate: null,
        inspectionEndDate: new Date("2026-02-15"),
        contractPrice: 178000,
        assignmentPrice: 182000,
        assignmentFee: null,
        buyerEmdAmount: null,
        buyerEmdReceived: false,
        titleCompany: "Capital Title",
        status: "UNDER_CONTRACT",
      },
      {
        id: d.D3,
        propertyAddress: "889 Maple Dr, Arlington, TX",
        sellerName: "James Wu",
        buyerName: "Open market",
        acquisitionsRepId: u.REP_ACQ_JORDAN,
        dispoRepId: u.REP_DISPO_ALEX,
        transactionCoordinatorId: u.TC,
        contractDate: new Date("2026-01-28"),
        assignedDate: null,
        closedFundedDate: null,
        inspectionEndDate: new Date("2026-02-20"),
        contractPrice: 210000,
        assignmentPrice: 215000,
        assignmentFee: null,
        buyerEmdAmount: 5000,
        buyerEmdReceived: false,
        titleCompany: "DFW Title Co",
        status: "MARKETED",
      },
      {
        id: d.D4,
        propertyAddress: "1204 Cedar Creek Rd, Plano, TX",
        sellerName: "Angela Ruiz",
        buyerName: "North Star LLC",
        acquisitionsRepId: u.REP_ACQ_SARAH,
        dispoRepId: u.REP_DISPO_CASEY,
        transactionCoordinatorId: u.TC,
        contractDate: new Date("2026-02-01"),
        assignedDate: null,
        closedFundedDate: null,
        inspectionEndDate: new Date("2026-02-25"),
        contractPrice: 165000,
        assignmentPrice: 172000,
        assignmentFee: null,
        buyerEmdAmount: 7500,
        buyerEmdReceived: false,
        titleCompany: "Premier Title",
        status: "BUYER_COMMITTED",
      },
      {
        id: d.D5,
        propertyAddress: "3310 Briarwood Ave, Irving, TX",
        sellerName: "Chris Patel",
        buyerName: "Bluebonnet Buyers",
        acquisitionsRepId: u.REP_ACQ_JORDAN,
        dispoRepId: u.REP_DISPO_ALEX,
        transactionCoordinatorId: u.TC,
        contractDate: new Date("2026-02-05"),
        assignedDate: null,
        closedFundedDate: null,
        inspectionEndDate: new Date("2026-02-28"),
        contractPrice: 142000,
        assignmentPrice: 148000,
        assignmentFee: null,
        buyerEmdAmount: 5000,
        buyerEmdReceived: true,
        titleCompany: "Metro Title",
        status: "EMD_RECEIVED",
      },
      {
        id: d.D6,
        propertyAddress: "908 Riverbend Dr, Garland, TX",
        sellerName: "Linda Ortiz",
        buyerName: "Summit Holdings",
        acquisitionsRepId: u.REP_ACQ_SARAH,
        dispoRepId: u.REP_DISPO_ALEX,
        transactionCoordinatorId: u.TC,
        contractDate: new Date("2026-02-08"),
        assignedDate: new Date("2026-02-26"),
        closedFundedDate: null,
        inspectionEndDate: new Date("2026-02-22"),
        contractPrice: 188000,
        assignmentPrice: 195000,
        assignmentFee: 12000,
        buyerEmdAmount: 10000,
        buyerEmdReceived: true,
        titleCompany: "Lone Star Title",
        status: "ASSIGNED",
      },
      {
        id: d.D7,
        propertyAddress: "2210 Summit View, McKinney, TX",
        sellerName: "Robert Hayes",
        buyerName: "Prairie Capital",
        acquisitionsRepId: u.REP_ACQ_JORDAN,
        dispoRepId: u.REP_DISPO_CASEY,
        transactionCoordinatorId: u.TC,
        contractDate: new Date("2026-02-10"),
        assignedDate: new Date("2026-02-27"),
        closedFundedDate: null,
        inspectionEndDate: new Date("2026-02-24"),
        contractPrice: 225000,
        assignmentPrice: 232000,
        assignmentFee: 15000,
        buyerEmdAmount: 15000,
        buyerEmdReceived: true,
        titleCompany: "Heritage Title",
        status: "ASSIGNED",
      },
      {
        id: d.D8,
        propertyAddress: "5540 Pinehurst Dr, Frisco, TX",
        sellerName: "Dana Kim",
        buyerName: "Evergreen RE LLC",
        acquisitionsRepId: u.REP_ACQ_JORDAN,
        dispoRepId: u.REP_DISPO_ALEX,
        transactionCoordinatorId: u.TC,
        contractDate: new Date("2025-11-12"),
        assignedDate: new Date("2025-12-01"),
        closedFundedDate: new Date("2026-01-08"),
        inspectionEndDate: new Date("2025-11-28"),
        contractPrice: 240000,
        assignmentPrice: 248000,
        assignmentFee: 12500,
        buyerEmdAmount: 12000,
        buyerEmdReceived: true,
        titleCompany: "First American",
        status: "CLOSED_FUNDED",
      },
      {
        id: d.D9,
        propertyAddress: "1902 Magnolia St, Denton, TX",
        sellerName: "Steve Nguyen",
        buyerName: "Red River LLC",
        acquisitionsRepId: u.REP_ACQ_SARAH,
        dispoRepId: u.REP_DISPO_CASEY,
        transactionCoordinatorId: u.TC,
        contractDate: new Date("2025-10-05"),
        assignedDate: new Date("2025-10-22"),
        closedFundedDate: new Date("2025-11-18"),
        inspectionEndDate: new Date("2025-10-18"),
        contractPrice: 132000,
        assignmentPrice: 138000,
        assignmentFee: 7500,
        buyerEmdAmount: 5000,
        buyerEmdReceived: true,
        titleCompany: "Champion Title",
        status: "CLOSED_FUNDED",
      },
      {
        id: d.D10,
        propertyAddress: "403 Winding Way, Richardson, TX",
        sellerName: "Priya Shah",
        buyerName: "Atlas Investors",
        acquisitionsRepId: u.REP_ACQ_JORDAN,
        dispoRepId: u.REP_DISPO_ALEX,
        transactionCoordinatorId: u.TC,
        contractDate: new Date("2025-09-01"),
        assignedDate: new Date("2025-09-18"),
        closedFundedDate: new Date("2025-10-12"),
        inspectionEndDate: new Date("2025-09-14"),
        contractPrice: 310000,
        assignmentPrice: 318000,
        assignmentFee: 18500,
        buyerEmdAmount: 15000,
        buyerEmdReceived: true,
        titleCompany: "Chicago Title",
        status: "CLOSED_FUNDED",
      },
      {
        id: d.D11,
        propertyAddress: "77 Broken Spoke Ln, Mesquite, TX",
        sellerName: "Tom Baker",
        buyerName: null,
        acquisitionsRepId: u.REP_ACQ_SARAH,
        dispoRepId: null,
        transactionCoordinatorId: u.TC,
        contractDate: new Date("2026-01-05"),
        assignedDate: null,
        closedFundedDate: null,
        inspectionEndDate: null,
        contractPrice: 98000,
        assignmentPrice: null,
        assignmentFee: null,
        buyerEmdAmount: null,
        buyerEmdReceived: false,
        titleCompany: "County Title",
        status: "CANCELED",
      },
      {
        id: d.D12,
        propertyAddress: "6000 Lakeside Blvd, Rockwall, TX",
        sellerName: "Elena Morales",
        buyerName: "Lakeview Capital",
        acquisitionsRepId: u.REP_ACQ_SARAH,
        dispoRepId: u.REP_DISPO_ALEX,
        transactionCoordinatorId: u.TC,
        contractDate: new Date("2025-08-10"),
        assignedDate: new Date("2025-08-28"),
        closedFundedDate: new Date("2025-09-30"),
        inspectionEndDate: new Date("2025-08-22"),
        contractPrice: 425000,
        assignmentPrice: 435000,
        assignmentFee: 22000,
        buyerEmdAmount: 20000,
        buyerEmdReceived: true,
        titleCompany: "Fidelity National",
        status: "CLOSED_FUNDED",
      },
    ],
  });

  await prisma.dealStatusHistory.createMany({
    data: [
      {
        dealId: d.D6,
        fromStatus: "EMD_RECEIVED",
        toStatus: "ASSIGNED",
        changedByUserId: u.ACQUISITIONS_MANAGER,
        note: "Buyer EMD cleared; assignment executed.",
      },
      {
        dealId: d.D8,
        fromStatus: "ASSIGNED",
        toStatus: "CLOSED_FUNDED",
        changedByUserId: u.TC,
        note: "Funded at closing.",
      },
    ],
  });

  await prisma.dealNote.createMany({
    data: [
      {
        dealId: d.D6,
        authorUserId: u.REP_DISPO_ALEX,
        body: "Buyer verified proof of funds. Working on assignment docs.",
      },
      {
        dealId: d.D8,
        authorUserId: u.TC,
        body: "Closed — wire confirmed. File archived.",
      },
    ],
  });
}
